### ISSUE TITLE
geting Error: DEVICE_NOT_OPENED with version.rs

### ISSUE THREAD

**Issue by StefanHri** [newAM/libftd2xx-rs#16]
I tried to run examples/version.rs. However, I am getting:
Library Version: 1.4.8
Error: DEVICE_NOT_OPENED

How to solve that?

**Comment by newAM** [comment]
What OS?

**Comment by StefanHri** [comment]
Ubuntu 20.04

**Comment by newAM** [comment]
Did you try the troubleshooting in the README?
https://github.com/newAM/libftd2xx-rs#troubleshooting

What do these two examples show?
```bash
cargo run --example list
cargo run --example list_fs
```

**Comment by newAM** [comment]
No response from author, closing issue.  Feel free to re-open if the issue still exists.
