### ISSUE TITLE
Ftdi::with_serial_number("xxxxx")? results: device not found

### ISSUE THREAD

**Issue by iamhuzhe-microleads** [newAM/libftd2xx-rs#4]
I can find FTDI device serial number with libftd2xx::list_devices() function, or FTID's FT_Prog GUI software. 

Once the serial number is used in "with_serial_number" function, it failed to open the device. 

"with_index(0)" can open the device correctly.

**Comment by newAM** [comment]
What operating system?  I have only tested this one on Linux myself.

**Comment by iamhuzhe-microleads** [comment]
Thanks for responding. I am on Windows 10 with rust 1.44.1

**Comment by newAM** [comment]
Interesting, I was able to reproduce this on Windows!  Works on the same PC dual booting Linux.

I'm pretty busy the next few days but I should be able to chase this down this weekend.

**Comment by newAM** [comment]
I think I found the problem.  This was broken on both platforms and it just happened to work on Linux.

The string was a rust native string which is not nul terminated.  I changed it to a `std::ffi::CString` which adds the trailing nul byte and it works on Windows now.

Version 0.3.2 includes the fix.  Let me know if this fixes it for you!

**Comment by iamhuzhe-microleads** [comment]
Yes, it works. Thanks
